### ISSUE TITLE
Renaming functions

### ISSUE THREAD

**Issue by sigmafelix** [Spatiotemporal-Exposures-and-Toxicology/Scalable_GIS#47]
Some functions, `distribute_*` in particular, give lint errors of variable names no longer than 30 characters. As rOpenSci requires a submission to pass lint checks, abbreviation of these function names is necessary. Naming conventions to consider are:

1. `{object type}_{function name}` as seen in `sf` functions (`st_*`) or `stringi` functions (`stri_*`)
2. Abbreviated not to overlap other generic function names as seen in `terra` (e.g., `vect`, `rast`, etc.)
3. `{function group}_{function name}_{specific use case}`: currently used, but will get shorter group and function names

Perhaps `distribute_*` are too verbose, so I am thinking of using `par` to represent parallelization (as `parallel` functions' `par*` naming). 

> `distribute_process_grid` to `pargrid` or `par_grid` or `parGrid`

- [x] Change function names
- [x] Edit vignettes and examples in functions
- [x] Pull to v0.3.0

**Comment by Spatiotemporal-Exposures-and-Toxicology** [comment]
@sigmafelix we can always make our own lints for naming. If you are able to come up with a clear naming convention that fits the default linters, then great. Otherwise, we can create a style. For example, the [cf-naming conventions](https://cfconventions.org/Data/cf-standard-names/docs/guidelines.html) have a defined style that results in long variable or function names
